language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t mmepani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mmepani/docker-react npm run test

